server:
  port: 3030
  host: localhost
  servlet:
    contextPath: /batch-processing

spring:
  application:
    name: batch-processing
  batch:
    jdbc:
      initialize-schema: 'always' #always #never
    job:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://${server.host}:<dbport>/spring_batch_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: <username>
    password: <password>
    jmx:
      default-domain: batch-processing
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none #none, create, create-drop, update <create | create-drop | update | validate | none>
      show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: UTC+1
        show_sql: false
    show-sql: true
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: false
            tablePrefix: QRTZ_
          scheduler:
            instanceName: MyScheduler
          threadPool:
            threadCount: 5
