server:
  port: 3030
  host: localhost
  servlet:
    contextPath: /batch-processing

spring:
  application:
    name: batch-processing
  batch:
    jdbc:
      initialize-schema: 'always' #always #never
    job:
      enabled: false
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: false
            tablePrefix: QRTZ_
          scheduler:
            instanceName: MyScheduler
          threadPool:
            threadCount: 5
